export const FACES = [
	{
		id: "about",
		text: "About",
		color: "--black-grey",
		image: "assets/dice_images/book.svg",
		rotation: { x: -0.044, y: 0.016, z: 0.000 },
		contentPath: "content/about.html",
	},
	{
		id: "contact",
		text: "Contact",
		color: "--dark-grey",
		image: "assets/dice_images/ball.svg",
		rotation: { x: -0.057, y: -1.538, z: 0.000 },
		contentPath: "content/contact.html",
	},
	{
		id: "blog",
		text: "Blog",
		color: "--mid-grey",
		image: "assets/dice_images/quill.svg",
		rotation: { x: 3.084, y: -0.004, z: 3.140 },
		contentPath: "content/blog.html",
	},
	{
		id: "now",
		text: "Now",
		color: "--light-grey",
		image: "assets/dice_images/sun.svg",
		rotation: { x: -2.559, y: 1.560, z: 2.499 },
		contentPath: "js/now/nowLoader.js",
	},
	{
		id: "projects",
		text: "Projects",
		color: "--lighter-grey",
		image: "assets/dice_images/cauldron.svg",
		rotation: { x: -1.904, y: 1.588, z: 0.005 },
		contentPath: "content/projects.html",
	},
];
